Repository yasmine-maarbani/quiz_game-Yasmine_MAARBANI-td1, pull requests merged in 2025-01, with the labels that each got.

#11 Update README.md
  README.md
Labels: documentation

#5 Solution proposal for the issue concerning the choice of answers
  quiz_game/main.py
Labels: enhancement

#7 Fix bug
  quiz_game/main.py
Labels: bug
